--
-- File generated with SQLiteStudio v3.4.4 on Mon May 8 15:04:24 2023
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Budget
CREATE TABLE IF NOT EXISTS Budget (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Amount INTEGER NOT NULL, Month INTEGER NOT NULL, CatName TEXT NOT NULL) STRICT;

-- Table: Category
CREATE TABLE IF NOT EXISTS Category (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, CatName TEXT NOT NULL, Amount INTEGER NOT NULL) STRICT;

-- Table: Expense
CREATE TABLE IF NOT EXISTS Expense (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, DayOfMonth INTEGER NOT NULL, Amount INTEGER NOT NULL, Budget ANY REFERENCES Budget (ID)) STRICT;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
